Repository googleapis/gapic-generator, pull requests merged in 2019-06, with the labels that each got.

#2784 SampleGen: namespace and imports in C#
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpStandaloneSampleTransformer.java
  src/main/java/com/google/api/codegen/util/csharp/CSharpAliasMode.java
  src/main/java/com/google/api/codegen/util/csharp/CSharpTypeTable.java
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: Core: Sample-gen, cla: yes

#2782 SampleGen: generate sample metadata
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpModelTypeNameConverter.java
  src/main/java/com/google/api/codegen/transformer/go/GoModelTypeNameConverter.java
  src/main/java/com/google/api/codegen/transformer/java/JavaModelTypeNameConverter.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSModelTypeNameConverter.java
  src/main/java/com/google/api/codegen/transformer/php/PhpModelTypeNameConverter.java
  src/main/java/com/google/api/codegen/transformer/py/PythonModelTypeNameConverter.java
  src/main/java/com/google/api/codegen/util/EscaperFactory.java
  src/main/java/com/google/api/codegen/util/Scanner.java
  src/main/java/com/google/api/codegen/viewmodel/MethodSampleView.java
  src/main/java/com/google/api/codegen/viewmodel/SampleFunctionParameterView.java
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/metadatagen/samplegen.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/InitCodeTransformerTest.java
  src/test/java/com/google/api/codegen/util/ScannerTest.java
Labels: Core: Sample-gen, cla: yes

#2813 node: fix failure when no options are passed
  src/main/resources/com/google/api/codegen/nodejs/main.snip
  src/main/resources/com/google/api/codegen/nodejs/test.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: cla: yes

#2810 SampleGen: Remove [START/END region_tag_core] region tags
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes

#2811 SampleGen: Hello unicode, bye bye six
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
Labels: cla: yes

#2801 Add GAPIC_CODE artifact type support for PHP
  src/main/java/com/google/api/codegen/discogapic/DiscoGapicGeneratorApp.java
  src/main/java/com/google/api/codegen/gapic/ArtifactFlags.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSurfaceTestTransformer.java
  src/test/java/com/google/api/codegen/gapic/GapicTestBase2.java
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_no_path_templates.baseline
Labels: cla: yes

#2820 SampleGen: parse floats from CLI
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes

#2796 C# Add ClientBuilder generation
  src/main/resources/com/google/api/codegen/csharp/gapic_client.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2819 SampleGen: Conform to Ruby style requirements
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes

#2821 Add GAPIC Bazel Extensions for PHP
  rules_gapic/README.md
  rules_gapic/gapic.bzl
  rules_gapic/gapic_pkg.bzl
  rules_gapic/go/go_gapic_pkg.bzl
  rules_gapic/java/java_gapic.bzl
  rules_gapic/java/java_gapic_pkg.bzl
  rules_gapic/php/BUILD.bazel
  rules_gapic/php/php_gapic.bzl
  rules_gapic/php/php_gapic_pkg.bzl
  rules_gapic/php/php_gapic_repositories.bzl
Labels: cla: yes

#2808 SampleGen: Choose the resource name that matches binding values for Oneof resource names
  src/main/java/com/google/api/codegen/config/ResourceNameOneofConfig.java
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2823 SampleGen: add SampleConfigProto
  src/main/proto/com/google/api/codegen/samplegen/v1/sample_config_v1.proto
Labels: cla: yes

#2825 node: use Buffer as a type for protobuf bytes
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSModelTypeNameConverter.java
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: cla: yes

#2822 SampleGen: C# response
  src/main/java/com/google/api/codegen/config/OutputContext.java
  src/main/java/com/google/api/codegen/transformer/OutputTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/util/EscaperFactory.java
  src/main/resources/com/google/api/codegen/csharp/response.snip
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: Core: Sample-gen, cla: yes

#2827 SampleGen: generate multi-line descriptions in sample metadata
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/MethodSampleView.java
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/metadatagen/samplegen.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, cla: yes

#2832 Propagate build errors for the `php` repository rule
  rules_gapic/php/php_gapic_repositories.bzl
Labels: cla: yes

#2839 C# Null-safe request-params header
  src/main/resources/com/google/api/codegen/csharp/gapic_client.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2836 Pass through channel creation options
  src/main/resources/com/google/api/codegen/py/transport.snip
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
Labels: cla: yes

#2841 Make `--package_yaml2` argument optional for Node.js generator
  src/main/java/com/google/api/codegen/config/PackageMetadataConfig.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
  src/main/java/com/google/api/codegen/packagegen/PackageGeneratorApp.java
  src/main/java/com/google/api/codegen/transformer/PackageMetadataTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSPackageMetadataTransformer.java
  src/main/resources/com/google/api/codegen/nodejs/README.md.snip
  src/main/resources/com/google/api/codegen/nodejs/package.json.snip
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: cla: yes

#2842 test: use artman image v0.26.0
  .circleci/config.yml
Labels: cla: yes

#2844 [feat] SampleGen: Parse empty object literals
  src/main/java/com/google/api/codegen/metacode/FieldStructureParser.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, cla: yes

#2831 SampleGen: Update Java templates
  src/main/resources/com/google/api/codegen/java/build_gapic_samples.gradle.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, cla: yes

#2845 Add GAPIC Bazel Extensions for Node.js
  rules_gapic/README.md
  rules_gapic/nodejs/BUILD.bazel
  rules_gapic/nodejs/nodejs_gapic.bzl
  rules_gapic/nodejs/nodejs_gapic_pkg.bzl
Labels: cla: yes

#2843 [fix] Allow package name to not start with "com.google"
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceNamer.java
Labels: cla: yes

#2828 SampleGen: parse the new sample config
  src/main/java/com/google/api/codegen/GeneratorMain.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/SampleConfig.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
  src/main/proto/com/google/api/codegen/samplegen/v1/sample_config_v1.proto
  src/test/java/com/google/api/codegen/config/GapicConfigProducerTest.java
  src/test/java/com/google/api/codegen/gapic/GapicTestBase2.java
Labels: Core: Sample-gen, cla: yes

#2852 Add sample_config.proto to the config_java_proto BUILD target
  BUILD.bazel
Labels: cla: yes

#2851 go: URL encode x-goog-request-params
  src/main/java/com/google/api/codegen/transformer/go/GoGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/transformer/go/GoImportSectionTransformer.java
  src/main/resources/com/google/api/codegen/go/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/go_library.baseline
Labels: cla: yes

#2856 Make it possible to pass metadata to the operations client
  .circleci/config.yml
  showcase/ruby/Gemfile
  src/main/resources/com/google/api/codegen/ruby/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
Labels: cla: yes

#2853 Python: Add client options.
  src/main/java/com/google/api/codegen/transformer/py/PythonImportSectionTransformer.java
  src/main/resources/com/google/api/codegen/py/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
Labels: Lang: Python, cla: yes, yoshi

#2857 Python: Sync 'list_*' method docstrings with implementation:
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
Labels: Lang: Python, cla: yes, yoshi

#2858 go: remove encoding on header request param key
  src/main/resources/com/google/api/codegen/go/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/go_library.baseline
Labels: cla: yes

#2860 Allow samplegen without sample configs
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
Labels: cla: yes

#2861 Fix string literal character escaping in Ruby generator
  src/main/java/com/google/api/codegen/transformer/ruby/RubyModelTypeNameConverter.java
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes
