Repository googleapis/gapic-generator, pull requests merged in 2019-04, with the labels that each got.

#2674 Deprecate license_file and license_header
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/util/LicenseHeaderUtil.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/license-header-bsd-3-clause.txt
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/longrunning_gapic.yaml
  src/test/java/com/google/api/codegen/util/LicenseHeaderUtilTest.java
Labels: cla: yes

#2675 Remove resource_name_treatment from testing and configgen
  src/main/java/com/google/api/codegen/configgen/mergers/MethodMerger.java
  src/main/resources/com/google/api/codegen/configgen/gapic_config.snip
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/longrunning_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/multiple_services_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/no_path_templates_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2677 Parse fixed resource names from regular CollectionConfigProto
  src/main/java/com/google/api/codegen/config/FixedResourceNameConfig.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/proto/com/google/api/codegen/config.proto
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2679 Parse field name patterns from proto options
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/util/ProtoParser.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/util/ProtoParserTest.java
Labels: cla: yes

#2680 Update Java google-common-protos to 1.15.0
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
Labels: cla: yes

#2688 Treat ResourceNameConfig.entityName as Name
  src/main/java/com/google/api/codegen/config/AnyResourceNameConfig.java
  src/main/java/com/google/api/codegen/config/FixedResourceNameConfig.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameMessageConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameOneofConfig.java
  src/main/java/com/google/api/codegen/config/SingleResourceNameConfig.java
  src/main/java/com/google/api/codegen/discogapic/transformer/DiscoGapicParser.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
  src/main/java/com/google/api/codegen/transformer/PathTemplateTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/main/proto/com/google/api/codegen/config.proto
Labels: cla: yes

#2689 Bug fixes for resource names
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameOneofConfig.java
  src/main/java/com/google/api/codegen/util/ProtoParser.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
Labels: cla: yes

#2678 Generate flattenings even if GAPIC config is not present
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2622 SampleGen: Print names of enum fields in PHP using Protobuf 3.7 helper method
  src/main/java/com/google/api/codegen/transformer/OutputTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
Labels: Status: Don't Merge, cla: yes

#2664 Remove proto_version from build.gradle; update protobuf-gradle plugin
  build.gradle
  dependencies.properties
  repositories.bzl
  showcase/ruby/Gemfile.lock
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
Labels: cla: yes

#2695 Fix empty method signature bug
  src/main/java/com/google/api/codegen/config/FlatteningConfig.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2660 SampleGen: C# unary and paged streaming templates
  src/main/java/com/google/api/codegen/config/DiscoGapicMethodContext.java
  src/main/java/com/google/api/codegen/config/GapicMethodContext.java
  src/main/java/com/google/api/codegen/config/MethodContext.java
  src/main/java/com/google/api/codegen/metacode/InitCodeNode.java
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/StaticLangApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaMethodViewGenerator.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/main/java/com/google/api/codegen/viewmodel/StaticLangApiMethodView.java
  src/main/resources/com/google/api/codegen/csharp/common.snip
  src/main/resources/com/google/api/codegen/csharp/common_initcode.snip
  src/main/resources/com/google/api/codegen/csharp/gapic_smoketest.snip
  src/main/resources/com/google/api/codegen/csharp/gapic_snippets.snip
  src/main/resources/com/google/api/codegen/csharp/gapic_unittest.snip
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
Labels: Core: Sample-gen, cla: yes

#2697 Update artman docker image
  .circleci/config.yml
Labels: cla: yes

#2698 AutoValue LongRunningConfig; always use gapic config's polling settings
  src/main/java/com/google/api/codegen/config/LongRunningConfig.java
  src/test/java/com/google/api/codegen/config/LongRunningConfigTest.java
Labels: cla: yes

#2694 Parse ResourceNames separately when annotations parsing is toggled on/off
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/SingleResourceNameConfig.java
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
Labels: cla: yes

#2685 Update protoc-java-resource-names-plugin
  repositories.bzl
Labels: cla: yes

#2701 Package-qualify resource references
  src/main/java/com/google/api/codegen/util/ProtoParser.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/book_from_anywhere.proto
  src/test/java/com/google/api/codegen/util/ProtoParserTest.java
Labels: cla: yes

#2704 ResourceNameOneofConfig fixes
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameOneofConfig.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2703 Start parsing GAPIC config v2
  BUILD.bazel
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/util/ConfigVersionValidator.java
Labels: cla: yes

#2702 Page streaming fix; optional fields fix
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/PageStreamingConfig.java
Labels: cla: yes

#2700 Oneof resource names in samples
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/book_from_anywhere.proto
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/util/ProtoParserTest.java
Labels: cla: yes

#2686 SampleGen: File output
  src/main/java/com/google/api/codegen/config/OutputContext.java
  src/main/java/com/google/api/codegen/transformer/OutputTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/StandardSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSampleOutputImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/MethodSampleView.java
  src/main/java/com/google/api/codegen/viewmodel/OutputView.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/common.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/response.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/OutputTransformerTest.java
Labels: cla: yes

#2707 Timeout millis is used by some languages
  src/main/proto/com/google/api/codegen/config.proto
Labels: cla: yes

#2708 Bring back timeout millis in GAPIC config v2
  src/main/proto/com/google/api/codegen/v2/config_v2.proto
Labels: cla: yes

#2711 Resource names across different protofiles
  src/main/java/com/google/api/codegen/config/FixedResourceNameConfig.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/SingleResourceNameConfig.java
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
Labels: cla: yes

#2712 Split proto parsing in GapicMethodConfig
  src/main/java/com/google/api/codegen/config/FlatteningConfig.java
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/LongRunningConfig.java
  src/main/java/com/google/api/codegen/config/PageStreamingConfig.java
  src/test/java/com/google/api/codegen/config/LongRunningConfigTest.java
Labels: cla: yes

#2714 Allow for "*" in resource_references
  src/main/java/com/google/api/codegen/util/ProtoParser.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
Labels: cla: yes

#2715 Refactor gapic method config
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/PageStreamingConfig.java
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
Labels: cla: yes

#2716 go: fix ignored page token bug in iterator
  src/main/resources/com/google/api/codegen/go/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
Labels: cla: yes

#2718 Fix missing default retries
  src/main/java/com/google/api/codegen/config/DiscoGapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/RetryCodesConfig.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/transformer/RetryDefinitionsTransformerTest.java
Labels: cla: yes

#2717 Bug fixes for gapic config v2 parsing
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/ProtoInterfaceModel.java
  src/test/java/com/google/api/codegen/config/GapicConfigProducerTest.java
  src/test/java/com/google/api/codegen/config/testdata/missing_interface_v1.yaml
Labels: cla: yes

#2713 SampleGen: default calling forms
  src/main/java/com/google/api/codegen/config/SampleConfig.java
  src/main/java/com/google/api/codegen/config/SampleSpec.java
  src/main/java/com/google/api/codegen/transformer/SampleFileRegistry.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpStandaloneSampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/main/java/com/google/api/codegen/viewmodel/OptionalArrayMethodView.java
  src/test/java/com/google/api/codegen/config/SampleSpecTest.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2722 Alphabetize SingleResourceNameConfigs
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
Labels: cla: yes

#2725 Cleanup + test
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/util/ProtoParser.java
  src/test/java/com/google/api/codegen/util/ProtoParserTest.java
Labels: cla: yes

#2726 Really alphabetize the SingleResourceNameConfigs
  src/main/java/com/google/api/codegen/config/DiscoGapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/InterfaceConfig.java
  src/main/java/com/google/api/codegen/transformer/PathTemplateTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
Labels: cla: yes

#2724 Config v2 tests
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/proto/com/google/api/codegen/v2/config_v2.proto
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
  src/test/java/com/google/api/codegen/protoannotations/GapicCodeGeneratorAnnotationsTest.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
Labels: cla: yes

#2729 SampleGen: sample package for Node.js
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/nodejs/NodeJSCodePathMapper.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSamplePackageMetadataTransformer.java
  src/main/resources/com/google/api/codegen/nodejs/sample_package.json.snip
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/frozen_dependencies.yaml
Labels: Core: Sample-gen, cla: yes

#2731 SampleGen: Change PHP sample file names to lower case
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
Labels: cla: yes

#2733 Update java-resource-names-plugin dependency to point to 0.0.13 commit
  repositories.bzl
Labels: cla: yes

#2727 Support new resource annotations
  .circleci/config.yml
  dependencies.properties
  src/main/java/com/google/api/codegen/config/DiscoGapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/FieldConfig.java
  src/main/java/com/google/api/codegen/config/FlatteningConfig.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/MethodConfig.java
  src/main/java/com/google/api/codegen/config/ResourceDescriptorConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameMessageConfig.java
  src/main/java/com/google/api/codegen/config/ResourceNameMessageConfigs.java
  src/main/java/com/google/api/codegen/config/ResourceNameOneofConfig.java
  src/main/java/com/google/api/codegen/config/SingleResourceNameConfig.java
  src/main/java/com/google/api/codegen/metacode/FieldStructureParser.java
  src/main/java/com/google/api/codegen/util/Name.java
  src/main/java/com/google/api/codegen/util/ProtoParser.java
  src/test/java/com/google/api/codegen/config/ResourceDescriptorConfigTest.java
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
  src/test/java/com/google/api/codegen/packagegen/testdata/library.proto
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/go_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/another_service.proto
  src/test/java/com/google/api/codegen/testsrc/common/book_from_anywhere.proto
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/testsrc/common/tagger.proto
  src/test/java/com/google/api/codegen/util/ProtoParserTest.java
Labels: cla: yes

#2737 Update protoc-java-resource-names-plugin for Bazel
  repositories.bzl
Labels: cla: yes
