Repository googleapis/gapic-generator, pull requests merged in 2019-03, with the labels that each got.

#2605 Move around test resources for protoc
  .circleci/config.yml
  src/test/java/com/google/api/codegen/config/GapicConfigProducerTest.java
  src/test/java/com/google/api/codegen/configgen/ConfigGenerationTest.java
  src/test/java/com/google/api/codegen/gapic/GapicCodeGeneratorTest.java
  src/test/java/com/google/api/codegen/protoannotations/GapicCodeGeneratorAnnotationsTest.java
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/testsrc/common/library.yaml
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/library_pkg2.yaml
  src/test/java/com/google/api/codegen/transformer/ModelTypeNameConverterTestUtil.java
  src/test/java/com/google/api/codegen/util/ProtoParserTest.java
Labels: cla: yes

#2607 Update bazel with newest common protos
  repositories.bzl
Labels: cla: yes

#2606 Implement ProtoGeneratorMain.main()
  build.gradle
  src/main/java/com/google/api/codegen/ProtocGeneratorMain.java
  src/main/java/com/google/api/codegen/gapic/ProtocGapicWriter.java
Labels: cla: yes

#2593 SampleGen: iterate over a map field in response handling
  src/main/java/com/google/api/codegen/transformer/OutputTransformer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSampleImportTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSampleOutputImportTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/OutputView.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, cla: yes

#2609 Remove extraneous @*Api annotations in snippet
  src/main/resources/com/google/api/codegen/java/grpc_stub.snip
  src/main/resources/com/google/api/codegen/java/http_stub.snip
  src/main/resources/com/google/api/codegen/java/main.snip
  src/main/resources/com/google/api/codegen/java/stub_interface.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2598 SampleGen: Import Longrunning Metadata in Java and and dependency of common-cli build.gradle
  src/main/java/com/google/api/codegen/config/DependenciesConfig.java
  src/main/java/com/google/api/codegen/config/PackageMetadataConfig.java
  src/main/java/com/google/api/codegen/transformer/java/JavaGapicSamplesPackageTransformer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSampleImportTransformer.java
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/frozen_dependencies.yaml
Labels: cla: yes

#2610 Fix Http Callables
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/StaticLangCallableFactoryView.java
  src/main/resources/com/google/api/codegen/java/http_callable_factory.snip
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
Labels: cla: yes

#2611 node: add .json extension to config require
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSImportSectionTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
Labels: cla: yes

#2615 Update gax version in CircleCI
  .circleci/config.yml
  .circleci/discogapic_compute_build.gradle
Labels: cla: yes

#2614 go: add pkg level doc for context use
  src/main/resources/com/google/api/codegen/go/doc.snip
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
Labels: cla: yes

#2603 SampleGen: Add an await pattern for LROs in Node.js
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSMethodViewGenerator.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/main/resources/com/google/api/codegen/nodejs/method_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
Labels: Core: Sample-gen, cla: yes

#2608 Refactor gapic-generator Bazel build
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  build.gradle
  dependencies.properties
  gapic_generator.bzl
  repositories.bzl
  repository_rules.bzl
  rules_gapic/gapic.bzl
  rules_gapic/java/java_gapic.bzl
  rules_gapic/java/java_gapic_pkg.bzl
  rules_gapic/java/java_gapic_pkg_deps_resolution.bzl
  rules_gapic/java/java_gapic_repositories.bzl
Labels: cla: yes

#2618 Add service level samples for Callable methods
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceTransformer.java
  src/main/resources/com/google/api/codegen/java/main.snip
  src/test/java/com/google/api/codegen/gapic/GapicCodeGeneratorTest.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
  src/test/java/com/google/api/codegen/testsrc/common/multiple_services.proto
Labels: cla: yes

#2617 SampleGen: Add missing response handling for methods without return value
  src/main/java/com/google/api/codegen/transformer/OutputTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, cla: yes

#2623 Reduce discogapic baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute.v1.json
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_gapic.yaml
Labels: cla: yes

#2613 SampleGen: generate sample function documentation
  src/main/java/com/google/api/codegen/config/SampleParameterConfig.java
  src/main/java/com/google/api/codegen/metacode/InitCodeNode.java
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/ApiMethodDocView.java
  src/main/java/com/google/api/codegen/viewmodel/MethodSampleView.java
  src/main/java/com/google/api/codegen/viewmodel/SampleFunctionDocView.java
  src/main/java/com/google/api/codegen/viewmodel/SampleFunctionParameterView.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, Type: Enhancement, cla: yes

#2626 Move python behind --dev_samples
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
Labels: Core: Sample-gen, cla: yes

#2628 SampleGen: Ruby groundwork
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/DynamicLangApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/StandardImportSectionTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonMethodViewGenerator.java
  src/main/java/com/google/api/codegen/transformer/py/PythonPackageMetadataTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyPackageMetadataTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/main/java/com/google/api/codegen/viewmodel/DynamicLangSampleView.java
  src/main/resources/com/google/api/codegen/ruby/initcode.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
Labels: Core: Sample-gen, cla: yes

#2629 api-common-java dep set to 1.7.0
  dependencies.properties
Labels: cla: yes

#2630 SampleGen: Fill out Ruby templates
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/FormattedInitValueView.java
  src/main/resources/com/google/api/codegen/ruby/response.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
Labels: Core: Sample-gen, cla: yes

#2635 Remove flattening_group_name
  src/main/java/com/google/api/codegen/config/SmokeTestConfig.java
  src/main/java/com/google/api/codegen/transformer/TestCaseTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicSmokeTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSPackageMetadataTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonPackageMetadataTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSurfaceTestTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyPackageMetadataTransformer.java
  src/main/proto/com/google/api/codegen/config.proto
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2639 Remove unused and not essential dependencies.
  BUILD.bazel
  build.gradle
  dependencies.properties
  src/test/java/com/google/api/codegen/metacode/SampleInitCodeTest.java
Labels: cla: yes

#2637 [configgen] Handle singular resource entities
  src/main/java/com/google/api/codegen/configgen/CollectionPattern.java
  src/test/java/com/google/api/codegen/configgen/CollectionPatternTest.java
Labels: cla: yes

#2619 Update python docs configuration file
  src/main/resources/com/google/api/codegen/py/docs/conf.py.snip
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
Labels: cla: yes

#2643 Paging methods must contain a page_size token to be a paged method
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2638 SampleGen: generate skeletons for C# standalone samples
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/StaticLangApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicClientTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpStandaloneSampleTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/StaticLangSampleClassView.java
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
Labels: Core: Sample-gen, cla: yes

#2642 Use "idempotent" and "non-idempotent" as default retry code def names
  src/main/java/com/google/api/codegen/config/RetryCodesConfig.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicClientTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/transformer/RetryDefinitionsTransformerTest.java
Labels: cla: yes

#2645 Change test resources for header_request_params
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2644 Generate header request params only from google.api.http
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/proto/com/google/api/codegen/config.proto
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2650 Allow disabling method generation in GAPIC config
  src/main/java/com/google/api/codegen/config/DiscoGapicInterfaceContext.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceContext.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/InterfaceContext.java
  src/main/java/com/google/api/codegen/transformer/MockServiceTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2641 SampleGen: generate comments on fields of request objects
  src/main/java/com/google/api/codegen/metacode/InitCodeNode.java
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/ListInitCodeLineView.java
  src/main/java/com/google/api/codegen/viewmodel/MapInitCodeLineView.java
  src/main/java/com/google/api/codegen/viewmodel/ReadFileInitCodeLineView.java
  src/main/java/com/google/api/codegen/viewmodel/SimpleInitCodeLineView.java
  src/main/java/com/google/api/codegen/viewmodel/StructureInitCodeLineView.java
  src/main/resources/com/google/api/codegen/java/initcode.snip
  src/main/resources/com/google/api/codegen/nodejs/init_code.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/sample_init.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/initcode.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: Core: Sample-gen, cla: yes

#2654 Update Showcase 0.0.13 for Java
  showcase/java/src/test/java/com/google/api/showcase/ShowcaseTest.java
Labels: cla: yes

#2651 Add @Deprecated to formatString[ResourceName] functions in Java
  src/main/java/com/google/api/codegen/transformer/PathTemplateTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/FormatResourceFunctionView.java
  src/main/java/com/google/api/codegen/viewmodel/ParseResourceFunctionView.java
  src/main/resources/com/google/api/codegen/java/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
Labels: cla: yes

#2655 [configgen] Fix comment indentation.
  src/main/java/com/google/api/codegen/configgen/ConfigGenerator.java
  src/main/resources/com/google/api/codegen/configgen/gapic_config.snip
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/longrunning_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/multiple_services_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/no_path_templates_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
Labels: cla: yes

#2657 Deprecate copyright_file in GAPIC config
  src/main/java/com/google/api/codegen/configgen/mergers/ConfigMerger.java
  src/main/java/com/google/api/codegen/configgen/transformer/DiscoConfigTransformer.java
  src/main/java/com/google/api/codegen/configgen/viewmodel/LicenseView.java
  src/main/java/com/google/api/codegen/util/LicenseHeaderUtil.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/configgen/gapic_config.snip
  src/test/java/com/google/api/codegen/config/testdata/missing_config_schema_version.yaml
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/longrunning_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/multiple_services_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/no_path_templates_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/longrunning_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/multiple_services_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/showcase_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/myproto_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/singleservice_gapic.yaml
  src/test/java/com/google/api/codegen/util/LicenseHeaderUtilTest.java
Labels: cla: yes

#2656 Treat UNSET_TREATMENT resource_name_type as STATIC_TYPES
  src/main/java/com/google/api/codegen/config/FieldConfig.java
  src/main/java/com/google/api/codegen/config/FlatteningConfig.java
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/MethodConfig.java
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_gapic.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2652 Remove flattening_group_name
  src/main/java/com/google/api/codegen/config/FlatteningConfig.java
  src/main/proto/com/google/api/codegen/config.proto
  src/test/java/com/google/api/codegen/config/ResourceNameMessageConfigsTest.java
Labels: cla: yes

#2659 Remove license header from configgen
  src/main/java/com/google/api/codegen/configgen/mergers/ConfigMerger.java
  src/main/java/com/google/api/codegen/configgen/transformer/DiscoConfigTransformer.java
  src/main/java/com/google/api/codegen/configgen/viewmodel/ConfigView.java
  src/main/java/com/google/api/codegen/configgen/viewmodel/LicenseView.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/configgen/gapic_config.snip
  src/test/java/com/google/api/codegen/config/testdata/missing_config_schema_version.yaml
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/longrunning_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/multiple_services_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/no_path_templates_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/multiple_services_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/showcase_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/myproto_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/singleservice_gapic.yaml
Labels: cla: yes

#2658 Remove language config option
  src/main/java/com/google/api/codegen/discogapic/DiscoGapicGeneratorApp.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
  src/main/proto/com/google/api/codegen/config.proto
  src/test/java/com/google/api/codegen/config/testdata/missing_config_schema_version.yaml
  src/test/java/com/google/api/codegen/gapic/ProtocGapicPluginGeneratorTest.java
  src/test/java/com/google/api/codegen/transformer/go/testdata/myproto_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/singleservice_gapic.yaml
Labels: cla: yes

#2662 SampleGen: update yargs to specify explicit types in Node.js
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
Labels: Core: Sample-gen, cla: yes

#2647 Remove GeneratedMessageV3 reffernces for the generated Java GAPIC clients
  .circleci/config.yml
  BUILD.bazel
  dependencies.properties
  rules_gapic/java/java_gapic_repositories.bzl
  showcase/java/src/test/java/com/google/api/showcase/ShowcaseTest.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceTestTransformer.java
  src/main/resources/com/google/api/codegen/java/grpc_test.snip
  src/main/resources/com/google/api/codegen/java/mock_service.snip
  src/main/resources/com/google/api/codegen/java/mock_service_impl.snip
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes

#2640 Generate all proto methods
  src/main/java/com/google/api/codegen/config/DiscoGapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
Labels: cla: yes

#2665 Add Gapic config v2
  src/main/proto/com/google/api/codegen/v2/config_v2.proto
Labels: cla: yes

#2667 Add test resources for google.api.http in client/bidi streaming
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2669 Don't use header request parameters for client/bidi streaming
  src/main/java/com/google/api/codegen/transformer/HeaderRequestParamTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2666 Whittling down config_v2
  src/main/proto/com/google/api/codegen/config.proto
  src/main/proto/com/google/api/codegen/v2/config_v2.proto
Labels: cla: yes

#2673 Remove implements_cancel & implements_delete
  src/main/java/com/google/api/codegen/config/LongRunningConfig.java
  src/main/java/com/google/api/codegen/transformer/LongRunningTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSurfaceTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/LongRunningOperationDetailView.java
  src/main/proto/com/google/api/codegen/config.proto
  src/main/resources/com/google/api/codegen/go/main.snip
  src/test/java/com/google/api/codegen/config/LongRunningConfigTest.java
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2671 Tag artman to 0.16.21
  .circleci/config.yml
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
Labels: cla: yes
