Repository googleapis/gapic-generator, pull requests merged in 2019-05, with the labels that each got.

#2741 [C#] Always generate the string param flattening method for resource-name methods
  src/main/java/com/google/api/codegen/config/FlatteningConfig.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaMethodViewGenerator.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2746 SampleGen: Use the correct default calling form in Java and Node.js
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
Labels: cla: yes

#2745 Bring paging back to GAPIC config v2
  src/main/java/com/google/api/codegen/config/GapicMethodConfig.java
  src/main/java/com/google/api/codegen/config/PageStreamingConfig.java
  src/main/proto/com/google/api/codegen/v2/config_v2.proto
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/go_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2750 PHP: Update gax version to 1.0.2
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
Labels: cla: yes

#2752 Remove all references of DEADLINE_EXCEEDED
  src/main/java/com/google/api/codegen/configgen/mergers/RetryMerger.java
  src/main/java/com/google/api/codegen/configgen/transformer/DiscoConfigTransformer.java
  src/test/java/com/google/api/codegen/config/testdata/missing_config_schema_version.yaml
  src/test/java/com/google/api/codegen/config/testdata/missing_interface_v1.yaml
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/longrunning_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/multiple_services_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/no_path_templates_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_gapic.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/go_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/longrunning_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/showcase_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/myproto_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/singleservice_gapic.yaml
Labels: cla: yes

#2749 SampleGen: Put Python and Ruby samples in samples/v1/
  src/main/java/com/google/api/codegen/gapic/CommonGapicCodePathMapper.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSamplesTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes

#2748 SampleGen: put PHP samples in the correct directory
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/php/PhpGapicCodePathMapper.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
Labels: cla: yes

#2755 SampleGen: Use Enum types before calling them
  src/main/java/com/google/api/codegen/config/OutputContext.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpSampleImportTransformer.java
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
Labels: cla: yes

#2754 SampleGen: Update Java template
  src/main/resources/com/google/api/codegen/java/initcode.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
Labels: cla: yes

#2758 Support "*" resource type
  src/main/java/com/google/api/codegen/config/ResourceNameMessageConfigs.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
Labels: cla: yes

#2743 Make gapic.bzl rules compliant with the standalone microgenerator spec
  rules_gapic/gapic.bzl
Labels: cla: yes

#2744 SampleGen: C# main method and CLIs
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpStandaloneSampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/MethodSampleView.java
  src/main/java/com/google/api/codegen/viewmodel/SampleFunctionParameterView.java
  src/main/resources/com/google/api/codegen/csharp/commandline.snip
  src/main/resources/com/google/api/codegen/csharp/common_initcode.snip
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: Core: Sample-gen, cla: yes

#2765 C# SampleGen: correct the output path of samples and add support for default calling forms for unary and paging
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpStandaloneSampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2768 Node: fix gax doc links that have been moved
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSApiMethodParamTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSSurfaceNamer.java
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: Lang: NodeJS, cla: yes, docs

#2769 remove the condition that is always false
  src/main/java/com/google/api/codegen/transformer/php/PhpSurfaceNamer.java
Labels: cla: yes

#2764 Add partial class resource names for C for resource types
  src/main/java/com/google/api/codegen/config/ResourceNameMessageConfigs.java
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
Labels: cla: yes

#2767 node: do not use lodash.merge, use latest gax
  .circleci/config.yml
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSImportSectionTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSPackageMetadataTransformer.java
  src/main/resources/com/google/api/codegen/nodejs/main.snip
  src/main/resources/com/google/api/codegen/nodejs/package.json.snip
  src/main/resources/com/google/api/codegen/nodejs/sample_package.json.snip
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/frozen_dependencies.yaml
Labels: cla: yes

#2772 Revert deadline exceeded removal
  src/main/java/com/google/api/codegen/configgen/mergers/RetryMerger.java
  src/main/java/com/google/api/codegen/configgen/transformer/DiscoConfigTransformer.java
  src/test/java/com/google/api/codegen/config/testdata/missing_config_schema_version.yaml
  src/test/java/com/google/api/codegen/config/testdata/missing_interface_v1.yaml
  src/test/java/com/google/api/codegen/configgen/testdata/library_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/longrunning_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/multiple_services_config.baseline
  src/test/java/com/google/api/codegen/configgen/testdata/no_path_templates_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_config.baseline
  src/test/java/com/google/api/codegen/discogapic/testdata/simplecompute_gapic.yaml
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/go/go_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/go_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/longrunning_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/showcase_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/myproto_gapic.yaml
  src/test/java/com/google/api/codegen/transformer/go/testdata/singleservice_gapic.yaml
Labels: cla: yes

#2775 Avoid coverage failure when no `_shared_modules` are present.
  src/main/resources/com/google/api/codegen/py/types.snip
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
Labels: Lang: Python, cla: yes, yoshi

#2777 SampleGen: Remove duplicate imports in Java
  src/main/java/com/google/api/codegen/transformer/StandardImportSectionTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: cla: yes

#2783 SampleGen: use application plugin in build.gradle of the sample package
  src/main/resources/com/google/api/codegen/java/build_gapic_samples.gradle.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
Labels: cla: yes

#2781 SampleGen: generate a Gemfile for ruby sample package
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorFactory.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubySamplePackageMetadataTransformer.java
  src/main/resources/com/google/api/codegen/ruby/Gemfile_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: cla: yes

#2776 SampleGen: Accept enum values as CLI flags
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/py/PythonSampleImportTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/SampleFunctionParameterView.java
  src/main/java/com/google/api/codegen/viewmodel/SimpleInitCodeLineView.java
  src/main/resources/com/google/api/codegen/csharp/commandline.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/library_v2_gapic.yaml
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2786 SampleGen: generate a correct Gemfile for ruby samples
  src/main/resources/com/google/api/codegen/ruby/Gemfile_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: Core: Sample-gen, cla: yes

#2788 SampleGen: use the correct default calling form for Java LRO methods
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
Labels: cla: yes

#2646 use the latest showcase
  .circleci/config.yml
  showcase/go/showcase_integration_test.go
  showcase/java/build.gradle
  showcase/java/src/test/java/com/google/api/showcase/ShowcaseTest.java
  showcase/nodejs/package.json
  showcase/nodejs/showcase-integration-test.js
  showcase/php/composer.json
  showcase/php/tests/ShowcaseIntegrationTest.php
  showcase/python/nox.py
  showcase/python/tests/showcase_integration_test.py
  showcase/ruby/Gemfile.lock
  showcase/ruby/showcase_integration_test.rb
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/artman_showcase.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/echo.proto
  src/test/java/com/google/api/codegen/testsrc/showcase/showcase.yaml
  src/test/java/com/google/api/codegen/testsrc/showcase/showcase_gapic.yaml
Labels: cla: yes

#2774 Make this anonymous inner class a lambda
  benchmark/clients/java/pubsub/src/main/java/com/google/cloud/bench/Pubsub.java
Labels: cla: yes

#2794 Update Ruby LRO sample snip (fix response variable)
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: Core: Sample-gen, cla: yes

#2795 Fix PHP LRO unit tests
  src/main/resources/com/google/api/codegen/php/test.snip
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
Labels: cla: yes

#2757 Sample: Use slashes instead of underscores in PHP namespaces for nested enums and messages
  src/main/java/com/google/api/codegen/transformer/php/PhpModelTypeNameConverter.java
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/myproto.proto
  src/test/java/com/google/api/codegen/transformer/ModelTypeNameConverterTestUtil.java
  src/test/java/com/google/api/codegen/transformer/php/PhpModelTypeNameConverterTest.java
  src/test/java/com/google/api/codegen/util/php/PhpTypeTableTest.java
Labels: Core: Sample-gen, cla: yes

#2800 node: make apiEndpoint an alias for servicePath
  src/main/resources/com/google/api/codegen/nodejs/main.snip
  src/main/resources/com/google/api/codegen/nodejs/test.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: cla: yes

#2802 Ruby: check both custom and wrapped exception types in unit tests
  src/main/resources/com/google/api/codegen/ruby/test.snip
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_longrunning.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_multiple_services.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
Labels: cla: yes

#2798 SampleGen: print `x.inspect` when x is a protobuf object
  src/main/java/com/google/api/codegen/transformer/ruby/RubySurfaceNamer.java
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
Labels: Core: Sample-gen, cla: yes

#2799 SampleGen: Clearer error message when parameter default values are not set
  src/main/java/com/google/api/codegen/metacode/InitCodeNode.java
Labels: Core: Sample-gen, cla: yes
