Repository googleapis/gapic-generator, pull requests merged in 2019-07, with the labels that each got.

#2846 [feat] SampleGen: comments on request object fields in C#
  src/main/resources/com/google/api/codegen/csharp/common_initcode.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: :rotating_light:, Core: Sample-gen, cla: yes

#2864 [fix] Generate helper methods for all resource names of a referenced oneof resource name
  src/main/java/com/google/api/codegen/transformer/PathTemplateTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/library.proto
  src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml
Labels: cla: yes

#2833 SampleGen: Add test sample configs in the new schema
  src/test/java/com/google/api/codegen/gapic/GapicCodeGeneratorTest.java
  src/test/java/com/google/api/codegen/gapic/GapicTestBase2.java
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/GapicCodeGeneratorAnnotationsTest.java
  src/test/java/com/google/api/codegen/testsrc/common/samplegen_config_migration_library_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/babble_about_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/delete_shelf.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/discuss_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/find_related_books.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_big_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_big_nothing.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_book_from_absolutely_anywhere.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_shelf.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/list_shelves.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/monolog_about_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/publish_series.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/stream_books.sample.yaml
Labels: Core: Sample-gen, cla: yes

#2869 C# Correctly escape request params headers
  src/main/resources/com/google/api/codegen/csharp/gapic_client.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2870 C# Add method to format resource-names
  src/main/resources/com/google/api/codegen/csharp/gapic_resourcenames.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2867 python: bump version bounds on iam dep
  src/main/java/com/google/api/codegen/transformer/py/PythonModelTypeNameConverter.java
  src/main/resources/com/google/api/codegen/packaging/dependencies.yaml
Labels: cla: yes

#2871 SampleGen: use sample config v1.2 in Ruby
  BUILD.bazel
  src/main/java/com/google/api/codegen/config/GapicProductConfig.java
  src/main/java/com/google/api/codegen/config/OutputContext.java
  src/main/java/com/google/api/codegen/config/SampleConfig.java
  src/main/java/com/google/api/codegen/config/SampleContext.java
  src/main/java/com/google/api/codegen/config/SampleParameterConfig.java
  src/main/java/com/google/api/codegen/gapic/GapicGeneratorApp.java
  src/main/java/com/google/api/codegen/metacode/InitCodeContext.java
  src/main/java/com/google/api/codegen/metacode/InitCodeNode.java
  src/main/java/com/google/api/codegen/transformer/DynamicLangApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java
  src/main/java/com/google/api/codegen/transformer/OutputTransformer.java
  src/main/java/com/google/api/codegen/transformer/SampleFileRegistry.java
  src/main/java/com/google/api/codegen/transformer/SampleTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/nodejs/NodeJSMethodViewGenerator.java
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/transformer/php/PhpMethodViewGenerator.java
  src/main/java/com/google/api/codegen/transformer/ruby/RubyGapicSamplesTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/main/java/com/google/api/codegen/viewmodel/DynamicLangSampleView.java
  src/main/java/com/google/api/codegen/viewmodel/MethodSampleView.java
  src/main/proto/com/google/api/codegen/samplegen/v1p2/sample_config_v1p2.proto
  src/main/resources/com/google/api/codegen/common.snip
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/main/resources/com/google/api/codegen/java/standalone_sample.snip
  src/main/resources/com/google/api/codegen/nodejs/standalone_sample.snip
  src/main/resources/com/google/api/codegen/php/standalone_sample.snip
  src/main/resources/com/google/api/codegen/py/standalone_sample.snip
  src/main/resources/com/google/api/codegen/ruby/standalone_sample.snip
  src/test/java/com/google/api/codegen/CodegenTestUtil.java
  src/test/java/com/google/api/codegen/gapic/GapicCodeGeneratorTest.java
  src/test/java/com/google/api/codegen/gapic/GapicTestBase2.java
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/ruby/ruby_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/GapicCodeGeneratorAnnotationsTest.java
  src/test/java/com/google/api/codegen/protoannotations/testdata/ruby_library.baseline
  src/test/java/com/google/api/codegen/testsrc/common/samples/babble_about_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/delete_shelf.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/discuss_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/find_related_books.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_big_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_big_nothing.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_book_from_absolutely_anywhere.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/get_shelf.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/list_shelves.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/monolog_about_book.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/publish_series.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/stream_books.sample.yaml
  src/test/java/com/google/api/codegen/testsrc/common/samples/test_optional_required_flattening_params.sample.yaml
  src/test/java/com/google/api/codegen/transformer/OutputTransformerTest.java
Labels: cla: yes

#2875 Use artman 0.30.0 for tests
  .circleci/config.yml
Labels: cla: yes

#2872 SampleGen: Generate LRO and gRPC streaming samples for C#
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpApiMethodTransformer.java
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpSurfaceNamer.java
  src/main/java/com/google/api/codegen/viewmodel/CallingForm.java
  src/main/resources/com/google/api/codegen/csharp/client.snip
  src/main/resources/com/google/api/codegen/csharp/common_initcode.snip
  src/main/resources/com/google/api/codegen/csharp/lro_sample.snip
  src/main/resources/com/google/api/codegen/csharp/paged_sample.snip
  src/main/resources/com/google/api/codegen/csharp/response.snip
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/main/resources/com/google/api/codegen/csharp/streaming_sample.snip
  src/main/resources/com/google/api/codegen/csharp/unary_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: cla: yes

#2878 Fix lro initial call settings
  src/main/resources/com/google/api/codegen/java/stub_settings.snip
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
Labels: cla: yes

#2879 Add @Generated to generated package-info files
  src/main/resources/com/google/api/codegen/java/package-info.snip
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
Labels: Lang: Java, cla: yes

#2881 fix(nodejs): drop dependency on through2
  showcase/nodejs/package.json
  src/main/resources/com/google/api/codegen/nodejs/package.json.snip
  src/main/resources/com/google/api/codegen/nodejs/test.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: Lang: NodeJS, cla: yes

#2882 Java: Remove unsupported retry samples
  src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicClientTransformer.java
  src/main/java/com/google/api/codegen/transformer/java/JavaSurfaceTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/SettingsDocView.java
  src/main/resources/com/google/api/codegen/java/settings.snip
  src/test/java/com/google/api/codegen/discogapic/testdata/java/java_simplecompute.v1.json.baseline
  src/test/java/com/google/api/codegen/gapic/GapicCodeGeneratorTest.java
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_my_streaming_proto.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/java/java_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/java_library_no_gapic_config.baseline
  src/test/java/com/google/api/codegen/testsrc/common/my_streaming_proto.proto
  src/test/java/com/google/api/codegen/testsrc/common/my_streaming_proto.yaml
  src/test/java/com/google/api/codegen/testsrc/common/my_streaming_proto_gapic.yaml
  src/test/java/com/google/api/codegen/testsrc/common/my_streaming_proto_pkg2.yaml
Labels: cla: yes

#2886 SampleGen: Adjust C# region tags location
  src/main/resources/com/google/api/codegen/csharp/commandline.snip
  src/main/resources/com/google/api/codegen/csharp/standalone_sample.snip
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/csharp/csharp_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/csharp_library.baseline
Labels: Core: Sample-gen, cla: yes

#2891 Python: Update google-api-core pin to '>= 1.14.0, < 2.0.0dev'.
  src/main/java/com/google/api/codegen/transformer/py/PythonPackageMetadataTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
Labels: Lang: Python, cla: yes, dependencies

#2890 Python: Fix docstrings for 'retry' arguments.
  src/main/java/com/google/api/codegen/transformer/py/PythonApiMethodParamTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
Labels: Lang: Python, cla: yes

#2896 Update intersphinx mappping for requests.
  src/main/resources/com/google/api/codegen/py/docs/conf.py.snip
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/py/python_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/python_library_no_gapic_config.baseline
Labels: Lang: Python, cla: yes, yoshi

#2899 fix(node): use apiEndpoint instead of servicePath in docs
  src/main/resources/com/google/api/codegen/nodejs/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: cla: yes

#2897 node: Call method without arguments or empty object
  src/main/resources/com/google/api/codegen/nodejs/main.snip
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_library.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_multiple_services.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_no_path_templates.baseline
  src/test/java/com/google/api/codegen/gapic/testdata/nodejs/nodejs_samplegen_config_migration_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/nodejs_library.baseline
Labels: cla: yes
