Repository googleapis/gapic-generator, pull requests merged in 2021-01, with the labels that each got.

#3325 update php paged map field snippets
  src/main/java/com/google/api/codegen/transformer/PageStreamingTransformer.java
  src/main/java/com/google/api/codegen/viewmodel/PageStreamingDescriptorView.java
  src/main/resources/com/google/api/codegen/php/method_sample.snip
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library_rest.baseline
Labels: cla: yes

#3319 fix: preserve the value of opt_args parameter
  rules_gapic/bazel/src/main/java/com/google/api/codegen/bazel/ApiVersionedDir.java
Labels: automerge, cla: yes

#3329 fix(build_gen): include httpbody import for java/go
  rules_gapic/bazel/src/main/java/com/google/api/codegen/bazel/BazelBuildFileView.java
  rules_gapic/bazel/src/test/data/googleapis/google/example/library/v1/BUILD.bazel.baseline
  rules_gapic/bazel/src/test/data/googleapis/google/example/library/v1/library.proto
Labels: api: cloudbuild, cla: yes

#3335 fix(python): use '\\' for string escapes
  rules_gapic/python/py_gapic.bzl
  rules_gapic/python/py_gapic_pkg.bzl
Labels: cla: yes

#3333 fix: PHP Use a deterministic ordering for rest placeholders
  src/main/java/com/google/api/codegen/transformer/php/PhpGapicSurfaceTransformer.java
  src/test/java/com/google/api/codegen/gapic/testdata/php/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library_rest.baseline
  src/test/java/com/google/api/codegen/protoannotations/testdata/php_library_with_grpc_service_config.baseline
Labels: cla: yes
